apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: secure-app
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
