apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: secure-app
data:
  mongo-init.js: |
    db.createUser({
      user: process.env.MONGO_INITDB_ROOT_USERNAME,
      pwd: process.env.MONGO_INITDB_ROOT_PASSWORD,
      roles: [
        {
          role: "readWrite",
          db: "mydatabase"
        }
      ]
    });
