apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: secure-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: MONGO_INITDB_DATABASE
          value: "mydatabase"
        volumeMounts:
        - name: mongo-config-volume
          mountPath: /docker-entrypoint-initdb.d
          subPath: mongo-init.js
      volumes:
      - name: mongo-config-volume
        configMap:
          name: mongodb-config
          items:
            - key: mongo-init.js
              path: mongo-init.js
