apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: secure-app
spec:
  hard:
    pods: "20"
    requests.cpu: "4"
    requests.memory: "16Gi"
    limits.cpu: "8"
    limits.memory: "32Gi"