apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secure-nginx-rolebinding
  namespace: secure-namespace
subjects:
- kind: User
  name: "developer"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: secure-nginx-role
  apiGroup: rbac.authorization.k8s.io